version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: alibaba-nginx
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - site

  app:
    build:
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
      context: ./
      dockerfile: Dockerfile
    image: alibaba-app
    container_name: alibaba-app
    depends_on:
      - database
    volumes:
      - ./:/var/www
    networks:
      - site
      - app

  database:
    image: mysql:8.0
    container_name: alibaba-database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-alibaba}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-alibaba_user}
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - app

volumes:
  database:

networks:
  site:
  app:
